version: '3'
services:
   Node1:
    image: p2ptest:1
    ports:
      - "8080:8080"
    entrypoint: ./go 127.0.0.1 Daniel :8080
   Node2:
    image: p2ptest:1
    links: 
    - Node1
    ports:
      - "8081:8080"
    entrypoint: ./go Node1 Helge :8081
   Node3:
    image: p2ptest:1
    links: 
    - Node1
    ports:
      - "8082:8080"
    entrypoint: ./go Node1 Kristian :8082
       

    